services:
  db:
    image: postgres:16
    container_name: corebank
    restart: always
    environment:
      POSTGRES_USER: onur
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: corebank_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    container_name: corebank-redis
    restart: always
    ports:
      - "6379:6379"

  mq:
    image: rabbitmq:3-management-alpine
    container_name: corebank-rabbitmq
    restart: always
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: onur
      RABBITMQ_DEFAULT_PASS: 12345
  seq:
    image: datalust/seq:latest
    container_name: corebank-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=12345
    ports:
      - "5341:5341"   
      - "8081:80"     
    volumes:
      - seq-data:/data
volumes:
  postgres_data:
  seq-data: